@startuml RustOrderクラス図
    class Main

    enum Status{
        PRINT,
        EXIT
    }
    
    class Excuter{
        - cummand: Command[]
        + excute()
    }

    class Print{
        
    }

    class CommandResult{
        commandResult : Object;
        Status
    }

    interface ICommand{
        + excute() : CommandResult
    }
    
    class Ls {}

    class CommandFactory{
        + CommandFactory(command: string) : Command[]
        - newCommand(commandName:string, option) : Command
    }

    'コマンドリザルト
    CommandResult *-> Status
    Main -> CommandFactory
    Main -down-> Excuter
    Excuter *-down-> ICommand
    Excuter -> Prin

    'コマンド
    ICommand -down-> CommandResult
    Ls .left.|> ICommand


@enduml