@startuml UI-コメント取得クラス図
    class MainWindow {
        + fun OnClickConnectCommentServerAsync()
        + fun OnClickDisconnectCommentServer();
    }
   
    interface UrlFormModel {
        - isConnect: bool
        - formUrl  : string
    }
    class TwicasUrlFormModel
    class NiconicoUrlFormModel

    interface CommentConnector{
        + ReadCommentAsync(): Task<CommentModel
    }
    class NiconicoCommentConnector
    class TwicasCommentConnector

    class CommentListView {
        + username: string
        + userIcon: Bitmap
        + comment : string
    }


    abstract class ConnectCommentServer
    note left of ConnectCommentServer
        モデル側のクラス
    end note

    'メインウィンドウ
    
    MainWindow -up-> UrlFormModel
    MainWindow --> CommentListView
    MainWindow -down-> CommentConnector

    'フォームモデル
    TwicasUrlFormModel   ..|> UrlFormModel
    NiconicoUrlFormModel ..|> UrlFormModel

    'コメントコネクター
    TwicasCommentConnector   ..|> CommentConnector
    NiconicoCommentConnector ..|> CommentConnector

    CommentConnector *--> ConnectCommentServer
    CommentConnector *-left-> CommentListView
    
@enduml