@startuml クラス図
    

    interface ICommand{
        + Excute(string[])
    }

    class CommandFactory{
        + FactoryCommand(string input)
    }

    class ShortcutSettingsManager{
        + Add((command,path))
        + Read()(command,path)[]

    }

    class Excuter{
        + ExcuteCommand()
    }

    
    Main -> CommandFactory
    
    CommandFactory -> ICommand
    CommandFactory *-down-> Excuter

    ShorcutCommand  .do.|> ICommand
    ShorcutCommand -> ShortcutSettingsManager
    RegisterCommand .left.|> ICommand

@enduml