@startuml シーケンス図

    actor -> CommandFactory : FactoryCommand(string[] コマンド) 
    activate CommandFactory
    alt 引数1がshorcut(仮)
        actor <-- CommandFactory : ShourtCutCommand
    else 引数1がregiste(仮)
        actor <-- CommandFactory : RegisteCommand
    end
    deactivate CommandFactory

    actor -> Excuter : ExcuteCommand()
    activate Excuter
    Excuter -> ICommand : Excute() : Result
    Excuter <-- ICommand : 結果 

    alt Result.None
        Excuter --> Excuter : none
    else Result.Failed
        Excuter --> Excuter : exit()
    else Result.Response
        Excuter --> Excuter : Anything()
    end

@enduml