@startuml コマンド
    actor User
    note left of User : ローカルに登録されているタグを管理する

    rectangle {
            User --> (タグを追加する)
            User --> (タグを編集する)
            User --> (タグを削除する)
            User --> (タグを確認する)
            
            (タグを追加する) --|> (タグを操作する)
            (タグを編集する) --|> (タグを操作する)
            (タグを削除する) --|> (タグを操作する)
            (タグを操作する) .|> (タグを管理する)
            (タグを確認する) ..|> (タグを管理する)
    }

    actor System
   
    rectangle {
        System --> (最新の記事が投稿されているかを確認)
        System --> (Qiita内に登録されているタグを確認)
        System --> (ユーザーに通知を送る)
        (最新の記事が投稿されているかを確認) --|> (Qiitaの情報を確認)
        (Qiita内に登録されているタグを確認) --|> (Qiitaの情報を確認)
    
    }

   
@enduml