@startuml ユーザー詳細情報Windowへの遷移
    MainWindow -> DropLogic : OpenUserInfoWindow(CommentModel)
    activate DropLogic

    DropLogic -> TwicasJsonConverter : ConvertToUserInfoViewModel
    activate TwicasJsonConverter
    DropLogic <-- JsonConverter : ユーザー詳細情報モデル
    deactivate TwicasJsonConverter
    DropLogic -> UserInfoFactory : FactroyUserInfoWindow(commentModel)
    activate UserInfoFactory
    UserInfoFactory --> UserInfoFactory : JudgeCreateWindow : UserInfoWindow
    DropLogic <-- UserInfoFactory : UserInfoWindow
    deactivate UserInfoFactory
    
    DropLogic -> UserInfoWindow : Show()
    deactivate DropLogic
@enduml
