POST https://twitcasting.tv/eventpubsuburl.php
Content-Type: multipart/form-data
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjMxMjFkMmVjOTliZWU3NmEzZTQ1MDlmYzg4ZWRjNjIyYjMxMzYwOGIyZjg3MTk5NjVhYjdmZGIwMmEyZDZiNGNiMTExNTQ0OTQ2NWVlNjhjIn0.eyJhdWQiOiIxMjc0MTYyNjEyMTMzOTU3NjMyLmMxMWNmMTVhZTE2NGE1YTY4MzVlMjcxNzRhZDYxZTkxNWQxMjE4MGJmMjRlZDgyNWQxYjM1ZjEyN2VhNWZhODciLCJqdGkiOiIzMTIxZDJlYzk5YmVlNzZhM2U0NTA5ZmM4OGVkYzYyMmIzMTM2MDhiMmY4NzE5OTY1YWI3ZmRiMDJhMmQ2YjRjYjExMTU0NDk0NjVlZTY4YyIsImlhdCI6MTYwNzExODAzNywibmJmIjoxNjA3MTE4MDM3LCJleHAiOjE2MjI2NzAwMzcsInN1YiI6IjEyNzQxNjI2MTIxMzM5NTc2MzIiLCJzY29wZXMiOlsicmVhZCIsIndyaXRlIl19.w9Csy_dXbUvE7P0xQMn7EqiY7SElB85Dsr4oVnjQ8IxWEgwVZUiqKjfYM32siiXftgMT6mECXcmowH6jQsK4vahGk-_--DPcqcaOZ8cQzu2srJOWCKFmAOKEHFseXGo3tfnAapdJajY-8suL8w-dh1ingElI7z4gvo0-chxYzCMFDujXv2qUphAqBLmFaDXZXKQsHEix5dSG0v1SbAFuOuVR3lKYiqPmQy__3WgzvsmQLdtNCvd5EKaviAh1Hr1LhNhIbyFokA_6pnqATVu-Vi0firvrg4OPMuvRppDxNUkZ7eH-g4DEZia0hOklmKYLuw0EiigaOFaR9IzHIZk48w
mode: cors
sec-fetch-site: same-Origin: 

{
  "movie_id": 654729746
}